"""Initial migration

Revision ID: cff889a1bb77
Revises: 
Create Date: 2026-01-29 00:01:15.419457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff889a1bb77'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('team_abbr', sa.String(length=20), nullable=True),
    sa.Column('runs', sa.Integer(), nullable=True),
    sa.Column('wickets', sa.Integer(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('strike_rate', sa.Float(), nullable=True),
    sa.Column('stat_type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('tid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('abbr', sa.String(length=20), nullable=False),
    sa.Column('alt_name', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('thumb_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('tid')
    )
    op.create_table('venues',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('venue_id')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('short_title', sa.String(length=100), nullable=True),
    sa.Column('subtitle', sa.String(length=100), nullable=True),
    sa.Column('match_number', sa.String(length=50), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=True),
    sa.Column('date_end', sa.DateTime(), nullable=True),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('teama_id', sa.Integer(), nullable=True),
    sa.Column('teamb_id', sa.Integer(), nullable=True),
    sa.Column('winning_team_id', sa.Integer(), nullable=True),
    sa.Column('status_str', sa.String(length=50), nullable=True),
    sa.Column('status_note', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('win_margin', sa.String(length=100), nullable=True),
    sa.Column('toss_winner_id', sa.Integer(), nullable=True),
    sa.Column('toss_decision', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['teama_id'], ['teams.tid'], ),
    sa.ForeignKeyConstraint(['teamb_id'], ['teams.tid'], ),
    sa.ForeignKeyConstraint(['toss_winner_id'], ['teams.tid'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.venue_id'], ),
    sa.ForeignKeyConstraint(['winning_team_id'], ['teams.tid'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('standings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('played', sa.Integer(), nullable=True),
    sa.Column('win', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('nr', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('netrr', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.tid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('standings')
    op.drop_table('matches')
    op.drop_table('venues')
    op.drop_table('teams')
    op.drop_table('player_stats')
    # ### end Alembic commands ###
